---
# ansible-playbook rgrouprole.yml -i hosts -v
- name: Ansible upload local to cloud
  hosts: selfserver
  tasks:
    - name: assign role to resource group
      shell: 'az role assignment create --role {{ az_role_id }} --assignee {{ item }}@00antonioperez00gmail.onmicrosoft.com --resource-group ResourceGroup{{ item }}'
      with_items:
        - A01702962
        - A01703026
        - A01702131
        - A01208984
        - A01365618
        - A01207531
        - A01702815
        - A01209075
        - A01700062
        - A01154844
        - A01209115
        - A01703291
        - A01209133
        - A01703658
        - A01208920
